#- name: Set Prompt
#  ansible.builtin.shell: set-prompt {{ tool_name }}
#
#
#- name: Download Hashicorp repo file
#  ansible.builtin.get_url:
#    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
#    dest: /etc/yum.repos.d/hashicorp.repo
#
#
#- name: install vault
#  ansible.builtin.dnf:
#    name: vault
#    state: installed
#
#- name: Copy Vault config
#  ansible.builtin.copy:
#    src: vault.hcl
#    dest: /etc/vault.d/vault.hcl
#
#- name: Start Vault Service
#  ansible.builtin.systemd_service:
#    name: vault
#    state: restarted

- name: Install and Configure Vault
  hosts: all
  become: true
  tasks:
    - name: Download HashiCorp repo file
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo

    - name: Install Vault
      ansible.builtin.dnf:
        name: vault
        state: present

    - name: Copy Vault config
      ansible.builtin.copy:
        src: vault.hcl
        dest: /etc/vault.d/vault.hcl
        owner: root
        group: root
        mode: '0644'

    - name: Enable and Restart Vault service
      ansible.builtin.systemd:
        name: vault
        state: restarted
        enabled: true

    - name: Open Vault port 8200 in firewall
      ansible.posix.firewalld:
        port: 8200/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Allow Vault port in SELinux
      ansible.builtin.command: semanage port -a -t http_port_t -p tcp 8200
      args:
        warn: false
      register: selinux_result
      failed_when: selinux_result.rc not in [0,1]  # ignore if already added
      changed_when: selinux_result.rc == 0
